micronaut:
  application:
    name: core
netty:
  default:
    allocator:
      max-order: 3
datasources:
  default:
    url: jdbc:sqlserver://localhost:1433;databaseName=accountserver
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: sa
    password: 'Y87dc#$98'
    schema-generate: CREATE_DROP
    dialect: SQL_SERVER
