micronaut:
  application:
    name: core
netty:
  default:
    allocator:
      max-order: 3
datasources:
  accountserver:
    url: jdbc:sqlserver://localhost:7508;databaseName=accountserver
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: sa
    password: 'Y87dc#$98'
    schema-generate: NONE
    dialect: SQL_SERVER
  gameserver:
    url: jdbc:sqlserver://localhost:7508;databaseName=gameserver
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: sa
    password: 'Y87dc#$98'
    schema-generate: NONE
    dialect: SQL_SERVER
jpa:
  default:
    properties:
      hibernate:
        physical_naming_strategy: "org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl"
        bytecode:
          provider: none

