micronaut:
  application:
    name: core
  router:
    versioning:
      enabled: true
      header:
        names:
          - 'X-API-VERSION'
          - 'Accept-Version'
netty:
  default:
    allocator:
      max-order: 3
datasources:
  default:
    url: jdbc:sqlserver://localhost:7508;databaseName=core
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: sa
    password: 'Y87dc#$98'
    dialect: SQL_SERVER
  accountserver:
    url: jdbc:sqlserver://localhost:7508;databaseName=accountserver
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: sa
    password: 'Y87dc#$98'
    schema-generate: NONE
    dialect: SQL_SERVER
  gameserver:
    url: jdbc:sqlserver://localhost:7508;databaseName=gameserver
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: sa
    password: 'Y87dc#$98'
    schema-generate: NONE
    dialect: SQL_SERVER
jpa:
  default:
    packages-to-scan:
      - 'com.kop.core'
  accountserver:
    properties:
      hibernate:
        physical_naming_strategy: "org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl"
        bytecode:
          provider: none
  gameserver:
    properties:
      hibernate:
        physical_naming_strategy: "org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl"
        bytecode:
          provider: none
flyway:
  datasources:
    default:
      enabled: true
      # default location: src/main/resources/db/migration
      locations: classpath:migrations/core